name: Build iOS with EAS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
     
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Cache CocoaPods
      uses: actions/cache@v4
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    
    - name: Cache Expo build artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.eas-build-local
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-eas-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-eas-
    
    - name: Setup Expo and EAS CLI
      run: npm install -g eas-cli
    
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit --no-fund
    
    - name: Run EAS Build for iOS (Unsigned)
      run: eas build --platform ios --profile unsigned --local --non-interactive --skip-credentials-check
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    
    - name: Upload Unsigned IPA Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: speedrail-ios-unsigned-${{ github.sha }}
        path: |
          **/*.ipa
        retention-days: 5