name: Build iOS with EAS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Setup Expo CLI
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Run EAS Build for iOS (Local)
      run: eas build --platform ios --local --non-interactive
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    
    - name: Build unsigned IPA with xcodebuild
      run: |
        cd ios
        xcodebuild -workspace Speedrail.xcworkspace -scheme Speedrail -configuration Release -sdk iphoneos -archivePath ./build/Speedrail.xcarchive archive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
        xcodebuild -exportArchive -archivePath ./build/Speedrail.xcarchive -exportPath ./build -exportOptionsPlist exportOptions.plist
    
    - name: Upload Unsigned IPA Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: speedrail-ios-unsigned-${{ github.sha }}
        path: |
          ios/build/*.ipa
        retention-days: 5