name: Build iOS IPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Dependencies
      run: |
        npm install
        cd ios
        pod install
    
    - name: Build iOS App
      run: |
        cd ios
        xcodebuild \
          -workspace Speedrail.xcworkspace \
          -scheme Speedrail \
          -configuration Release \
          -archivePath $PWD/build/Speedrail.xcarchive \
          clean archive
    
    - name: Create IPA
      run: |
        cd ios
        xcodebuild \
          -exportArchive \
          -archivePath $PWD/build/Speedrail.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath $PWD/build
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: ios/build/*.ipa
